name: Prueba automatizada

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Instalar dependencias
        working-directory: src
        run: pip install -r requirements.txt

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Ejecutar pruebas con pytest
        working-directory: src
        run: pytest tests.py

  integrado:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Mensaje de integración
        run: echo "Integrado a main"
